### ISSUE TITLE
Erro ao execultar na WEB, SSL e CORS origin

### ISSUE THREAD

**Issue by d3roch4** [marcobraghim/sigepweb#1]
Quando tentei rodar na web obtive o seguinte erro:
`
main.dart.js:43400 Mixed Content: The page at 'https://****.web.app/flor-de-menina#/loja/1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo?nCdEmpresa=08082650&sDsSenha=564321&nCdServico=04014%2C04510&sCepOrigem=74003000&sCepDestino=47740000&nVlPeso=1&nCdFormato=1&nVlComprimento=20&nVlAltura=20&nVlLargura=20&nVlDiametro=0&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml&nIndicaCalculo=3'. This request has been blocked; the content must be served over HTTPS.
an0 @ main.dart.js:43400
`

Entaão alterei passa HTTPS e obtive outro erro:
`
lor-de-menina#/loja/1:1 Access to XMLHttpRequest at 'https://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo?nCdEmpresa=08082650&sDsSenha=564321&nCdServico=04014%2C04510&sCepOrigem=74003000&sCepDestino=47740000&nVlPeso=1&nCdFormato=1&nVlComprimento=20&nVlAltura=20&nVlLargura=20&nVlDiametro=0&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml&nIndicaCalculo=3' from origin 'https://****.web.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.dart.js:4035 Erro interno do package. Por favor considere abrir uma questão em https://github.com/marcobraghim/sigepweb/issues
Mensagem da exception foi: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error. 
stack: Erro interno do package. Por favor considere abrir uma questão em https://github.com/marcobraghim/sigepweb/issues
`

**Comment by marcobraghim** [comment]
Ola, muito obrigado por ter aberto essa questão!

Eu não tenho tido tempo para mexer nesse package, então não sei exatamente quando vou poder mexer nisso.

Qualquer pessoa pode fazer um fork deste projeto e ajudar a resolver este problema, depois fazer um Pull Request aqui, a comunidade ficará muito grata!

Para tornar esse caminho mais fácil já deixo aqui um link que pode dar uma boa pista do que está acontecendo e como resolver:
https://stackoverflow.com/questions/10456591/cors-with-dart-how-do-i-get-it-to-work

Eu acredito que bastará adicionar o header **Access-Control-Allow-Origin** com valor *

**Comment by marcobraghim** [comment]
Resolvido pelo PR
